trailingComma: es5
tabWidth: 4
bracketSameLine: true
semi: true
printWidth: 120
singleAttributePerLine: false
overrides:
  - files: "*.yml"
    options:
      tabWidth: 2
      singleQuote: true
  - files: "*.json"
    options:
      tabWidth: 2
